### ISSUE TITLE
where is the ascenddk-private in https://github.com/Ascend?

### ISSUE THREAD

**Issue by 760153699** [Ascend/ascenddk#106]
**where is the ascenddk-private in https://github.com/Ascend?**
我无法下载软件包

**Comment by wzh19960730** [comment]
> **where is the ascenddk-private in https://github.com/Ascend?**
> 我无法下载软件包

me too...have you found it?

**Comment by paojiaozhuazhua** [comment]
where is？？？

**Comment by swxEmily** [comment]
Tools packages now are in private git for cooperative enterprise, haven't been published.  Please send mail to our email account: ascend@huawei.com to get the authority.

**Comment by summershrimp** [comment]
Where can I buy a atlas 200 dk board? Or can I borrow one inside huawei?

**Comment by paojiaozhuazhua** [comment]
好像是非卖品，得向华为申请




------------------ 原始邮件 ------------------
发件人: "Yibai Zhang"<notifications@github.com>;
发送时间: 2019年4月18日(星期四) 下午4:20
收件人: "Ascend/ascenddk"<ascenddk@noreply.github.com>;
抄送: "浅 唱、"<1056082935@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [Ascend/ascenddk] where is the ascenddk-private inhttps://github.com/Ascend? (#106)




Where can I buy a atlas 200 dk board? Or can I borrow one inside huawei?

**Comment by swxEmily** [comment]
Sales channels are in preparation. Atlas200 is ready for sale on the vmall platform in May, You can follow the website message.

**Comment by summershrimp** [comment]
@swxEmily I'm a huawei employee, Is there any method to apply/borrow one inside Huawei?

**Comment by paojiaozhuazhua** [comment]
这个不太清楚，我是一名大学生，华为和高校有合作，我的老师收到华为寄来的开发板，然后他借给了我们使用，华为员工应该更好在内部要到吧。
This is not very clear. I am a college student. Huawei and the university have cooperated. My teacher received the development board from Huawei. Then he lent it to us. Huawei employees should better come inside.


------------------ 原始邮件 ------------------
发件人: "Yibai Zhang"<notifications@github.com>;
发送时间: 2019年4月19日(星期五) 中午1:29
收件人: "Ascend/ascenddk"<ascenddk@noreply.github.com>;
抄送: "浅 唱、"<1056082935@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [Ascend/ascenddk] where is the ascenddk-private inhttps://github.com/Ascend? (#106)




@swxEmily I'm a huawei employee, Is there any method to apply/borrow one inside Huawei?

**Comment by swxEmily** [comment]
@summershrimp please send your huawei account to ascend@huawei.com
