### ISSUE TITLE
can't find available ip when run deploy.sh

### ISSUE THREAD

**Issue by yuanliwei23** [Ascend/ascenddk#118]
**Describe the bug**
We can not find available Ip when hint "Please choose one which can connect to Atlas DK Developerment Board:" 

**To Reproduce**
1. Step1
bash deploy.sh 192.168.4.13 internet
2. Step2
when hint "Please choose one which can connect to Atlas DK Developerment Board:",can not find available Ip in valid ip list

**Expected behavior**
The "192.168.4.133" can be found in ip list

**Current behavior**
can not find "192.168.4.133" in ip list

**Screenshots**

![image](https://user-images.githubusercontent.com/45615023/56110441-0e7ff000-5f87-11e9-8ec7-9f879ae74c2b.png)

![image](https://user-images.githubusercontent.com/45615023/56110466-28b9ce00-5f87-11e9-8f94-954db2d815b0.png)

![image](https://user-images.githubusercontent.com/45615023/56110515-60287a80-5f87-11e9-8412-213ddaf60c1e.png)

**Your environment : **

**Ascenddk Version : **
1.3.13.800

**Developer Board Version : **
1.3.13.800

**Comment by swxEmily** [comment]
Scripts use ipconfig command to check the ips, from your information, the virtual ip cannot show by ifconfig. 
We will change to support it.
