### ISSUE TITLE
B650 DDK无法通过git下载

### ISSUE THREAD

**Issue by atlascollege** [Ascend/ascenddk#12]
**Describe the bug**
基于私仓地址下载DDK的：https://github.com/Ascend/ascenddk-private

**To Reproduce**
1. Step1：git clone https://github.com/Ascend/ascenddk-private
![image](https://user-images.githubusercontent.com/45622094/50680559-199bb980-1043-11e9-8917-0ae123f80d65.png)
![image](https://user-images.githubusercontent.com/45622094/50680611-464fd100-1043-11e9-8e77-7e08214ead76.png)
error: RPC failed; curl 56 GnuTLS recv error (-110): The TLS connection was non-properly terminated.

安装包太大，超过500M的最大内存，导致下载失败；参考网上的多种方法均无法解决
https://blog.csdn.net/qq_34121797/article/details/79561110
https://blog.csdn.net/congcong7267/article/details/81413531

建议：针对不同的B版本建立不同的git分支，单独下某个B版本的包；而不是B590，B650所有的B版本
针对安装包太大的场景，在论坛给出可行的解决方法

**Expected behavior**
下载成功

**Current behavior**
A clear and concise description of what happens currently.

**Screenshots**

**Your environment : **

**Ascenddk Version : **

**Developer Board Version : **

**Additional context**
Add any other context about the problem here.(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, etc)

**Comment by ascendhuawei** [comment]
1、当前我们是beta版，后续会针对不同的B版本建立不同的分支，保证主干上只有一个包；
2、如果紧急使用当前的包，可以只下载使用包暂时规避
3、后续我们会优化对应的git命令，使用户能用git命令下载成功
