### ISSUE TITLE
libz.so not found

### ISSUE THREAD

**Issue by jiangcxia** [Ascend/ascenddk#18]
B650SP07版本：
[STDOUT] - do [do_pre_build]
[STDOUT] [LD] /projects/TEST/out/main
[STDOUT] /usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: warning: libz.so.1, needed by /home/jiangcxia/studiob650/tools/che/ddk/ddk/host/lib//libprotobuf.so, not found (try using -rpath or -rpath-link)
[STDOUT] /home/jiangcxia/studiob650/tools/che/ddk/ddk/host/lib//libprotobuf.so: undefined reference to `inflateInit2_'
[STDOUT] /home/jiangcxia/studiob650/tools/che/ddk/ddk/host/lib//libprotobuf.so: undefined reference to `inflate'
[STDOUT] /home/jiangcxia/studiob650/tools/che/ddk/ddk/host/lib//libprotobuf.so: undefined reference to `deflateInit2_'
[STDOUT] /home/jiangcxia/studiob650/tools/che/ddk/ddk/host/lib//libprotobuf.so: undefined reference to `deflate'
[STDOUT] /home/jiangcxia/studiob650/tools/che/ddk/ddk/host/lib//libprotobuf.so: undefined reference to `deflateEnd'
[STDOUT] /home/jiangcxia/studiob650/tools/che/ddk/ddk/host/lib//libprotobuf.so: undefined reference to `inflateEnd'
[STDOUT] collect2: error: ld returned 1 exit status
[STDOUT] Makefile:77: recipe for target '/projects/TEST/out/main' failed
[STDOUT] make: *** [/projects/TEST/out/main] Error 1
报缺少libz.so
资料中少了一步，需要将./sysroot/lib/aarch64-linux-gnu拷贝出来。
cp -rdp ./sysroot/lib/aarch64-linux-gnu/* /usr/aarch64-linux-gnu/lib
之后，可以解决问题。

**Comment by swxEmily** [comment]
document have added the step.[https://www.huawei.com/minisite/ascend/cn/filedetail_2.html](url)
